blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'
urlpatterns = [
    path('', views.blog_home, name="blog_home"),
    path('about/', views.blog_about, name="blog_about"),
    path('<int:year>/<int:month>/<int:day>/<slug:post_slug>/', 
          views.post_details, name="post_details"),
]

multi_user_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from blog import views
from users import views as users_views 

from django.conf import settings 
from django.conf.urls.static import static 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('register/', users_views.register, name="register"),
    path('profile/', users_views.profile, name="profile"),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('edit/', users_views.edit, name='edit'),
    # forward any request with blog/ to the blog.urls.py
    path('blog/', include("blog.urls", namespace='blog')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, 
                                        document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

# create a manager for retrieving published posts
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self)\
            .get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )

    # post attributes or fields
    title = models.CharField(max_length=250)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    date_published = models.DateTimeField(default=timezone.now)
    date_updated = models.DateTimeField(auto_now=True)
    date_created = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=250, unique_for_date='date_published')
    status = models.CharField(max_length=10,
                                choices=STATUS_CHOICES, 
                                default='draft')
    
    # order according to most recent post
    class Meta:
        ordering = ('-date_published',)
    # string representation of post
    def __str__(self):
        return self.title

    # methods for getting absolute url
    # reverse() allows you to build a url
    def get_absolute_url(self):
        return reverse('blog:post_details',
                       args=[self.date_published.year,
                             self.date_published.month,
                             self.date_published.day, 
                             self.slug])

    # define managers 
    objects = models.Manager() # default manager
    published = PublishedManager() #custom manager


    








    

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse 
from .models import Post
# Create your views here.

def home(request):
    return HttpResponse('<h1>This is the project page</h1>')

def blog_home(request):
    # retrieve all posts

    all_posts = Post.published.all()
    #all_posts = Post.objects.all()
    return render(request,"blog/home.html", {"posts": all_posts})

def post_details(request, year, month, day, post_slug):
    # use shortcut to get specific object 

     #status='published',
    post = get_object_or_404(Post, slug=post_slug,
                                    date_published__year=year,
                                    date_published__month=month,
                                    date_published__day=day)
    return render(request, 'blog/details.html', {'post':post})

def blog_about(request):
    contents = "Hi, this blog is a platform for several users"
    title = "About"
    return render(request,"blog/about.html", {"about_contents":contents, "title":title})

blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block content %}


    <h1> This is the blog-about page </h1>
    {{about_contents}}

{% endblock content %}

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS from the bootstrap starter template -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


    <!-- load the static file -->
    {% load static %}
    <link rel="stylesheet" type="text/css"  href="{% static 'blog/style.css' %}"> 

</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'home' %}">Home</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{% url 'blog:blog_home' %}">Blog</a>
                <a class="nav-item nav-link" href="{% url 'blog:blog_about' %}">About</a>
              </div>
              
              <!-- Navbar login and register -->
              <div class="navbar-nav">
                {% if user.is_authenticated %}
                  <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                  <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                {% else %}
                  <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                  <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
      </header>
      <!--  <main> represents the dominant content of the <body> -->
      <main role="main" class="container">
        <div class="row">
          <div class="col-md-8">
           <!-- display messages here -->
            {% if messages %}
              {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}

            {% block content %}{% endblock %}
          </div>
          <div class="col-md-4">
            <div class="content-section">
              <h3> Sidebar </h3>
              <p class='text-muted'>Find the latest posts and announcements here
                <ul class="list-group">
                  <li class="list-group-item list-group-item-light">Latest Posts</li>
                  <li class="list-group-item list-group-item-light">Announcements</li>
                </ul>
              </p>
            </div>
          </div>
        </div>
      </main>
  
    <!-- Optional JavaScript -->
    <!-- Option 1: Bootstrap Bundle with Popper from bootstrap starter template-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% block content %}

    <!-- loop through the post object and display its attributes --> 
    {% for post in posts %}
    <article class="media content-section">
        <img class="rounded-circle account-img" src="{{ post.author.profile.image.url }}">
        <div>
            <div class="article-metadata">
                <h2 ><a class="article-title" href="{{ post.get_absolute_url }}">  {{ post.title }} </a></h2>
                <small class="text-muted"> By {{ post.author }} on {{ post.date_published|date:"F d, Y" }}</small>
            </div>
            <p class="article-content">{{ post.content|truncatewords:30|linebreaks }}</p>
        <div>   
    </article>
    {% endfor %}

{% endblock content  %}
